spring:
  datasource:
    url: jdbc:sqlite:users.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true
  
server:
  port: 8080
  
logging:
  level:
    com.example.usermanagement: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE